
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: demo-connect
            items:
              - key: application.properties
                path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /deployments/config
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
      serviceAccount: ribbon
