apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-demo
spec:
  backup:
    managed: true
    image: registry.connect.redhat.com/couchbase/operator-backup:latest
    serviceAccountName: couchbase-backup
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    selector:
      matchLabels:
        cluster: cb-demo
