apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: demo
  labels:
    cluster: cb-demo
spec:
  name: demo
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: high
  evictionPolicy: valueOnly
  conflictResolution: lww
  enableFlush: false
  enableIndexReplica: true
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: demo-attachments
  labels:
    cluster: cb-demo
spec:
  name: demo_attachments
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: high
  evictionPolicy: valueOnly
  conflictResolution: lww
  enableFlush: false
  enableIndexReplica: true
  compressionMode: passive

