apiVersion: v1
kind: Secret
metadata:
  name: sgw-user-rbac
data:
  password: cGFzc3dvcmQ= # This password is the literal "password". The correctly encoded form can be generated on a "UNIX-like" command line terminal with echo -n 'password' | base64.
---
apiVersion: couchbase.com/v2
kind: CouchbaseUser
metadata:
  name: sync-gateway-user
  labels:
    cluster: cb-demo
spec:
  authDomain: local
  authSecret: sgw-user-rbac
---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: sync-gateway-group
spec:
  roles:
  - name: bucket_full_access
    bucket: demo
  - name: bucket_full_access
    bucket: demo_attachments
---
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: sgw-user-rolebinding
spec:
  subjects:
  - kind: CouchbaseUser
    name: sync-gateway-user
  roleRef:
    kind: CouchbaseGroup
    name: sync-gateway-group
