apiVersion: v1
kind: Service
metadata:
  name: sync-gateway-service
spec:
  ports:
    - name: apiport
      port: 4984
      targetPort: 4984
      protocol: TCP
  type: "NodePort"
  selector:
    app: sync-gateway
